--- 
title: "Econometrics and Statistics"
author: "Jean-Paul Renne"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This course covers various topics in econometrics. Simulations and real-data-based examples are provided."
css: "my-style.css"
---

<!-- Declare new latex code: -->
\newcommand{\bv}[1]{\mathbf{#1}} 

# Econometrics and statistics {#intro .unlisted .unnumbered}

<!-- # Before starting {#intro .unlisted .unnumbered} -->

This course covers various econometric topics, including linear regression models, discrete-choice models, and an introduction to time series analysis. It provides examples or simulations based on R codes. This course has been developed by [Jean-Paul Renne](https://www.jprenne.com).

The R codes use various packages that can be obtained from [CRAN](https://cran.r-project.org). Several pieces of code also involve procedures and data from a companion package (`AEC`). This `AEC` package is available on GitHub. To install it, one need to employ the `devtools` library:

```{r installAEC, eval=FALSE}
install.packages("devtools") # This library allows to use "install_github".
library(devtools)
install_github("jrenne/AEC")
library(AEC)
```

**Useful (R) links:**

* Download R:

    *	R software: https://cran.r-project.org (the basic R software)
    *	RStudio: https://www.rstudio.com (a convenient R editor)

* Tutorials:

    *	Rstudio: https://dss.princeton.edu/training/RStudio101.pdf (by Oscar Torres-Reyna)
    *	R: https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf (by Emmanuel Paradis)
    * My own tutorial: https://jrenne.shinyapps.io/Rtuto_publiShiny/







