# Synthetic fixtures only: no private teaching material is needed.
source("R/exercises.R")
source("R/instructor-build.R")
fixture <- tempfile("edition-check-"); dir.create(fixture)
original <- getwd()
tryCatch({
  book <- file.path(fixture,"book"); dir.create(book)
  bank <- file.path(book,"exercises","basics"); dir.create(bank,recursive=TRUE)
  private <- file.path(fixture,"private"); dir.create(private)
  writeLines(c("---","id: example","title: Example","difficulty: Core",
    "type: Calculation","related: basics","---","## Statement","Find the mean."),file.path(bank,"01-example.md"))
  writeLines(c("---","id: example","---","## Hint","PRIVATE_HINT",
    "## Solution","PRIVATE_ANSWER"),file.path(private,"07-answer.md"))
  writeLines(c("---","params:","  show_solutions: false","---"),file.path(book,"index.Rmd"))
  stopifnot(!edition_setting(file.path(book,"index.Rmd")))
  Sys.setenv(ECOSTAT_BOOK_ROOT=book,ECOSTAT_INSTRUCTOR_DIR=private)
  setwd(book)
  configure_edition(FALSE)
  student <- as.character(render_exercises("basics"))
  stopifnot(!grepl("PRIVATE_",student),grepl("Find the mean",student))
  error <- tryCatch({configure_edition(TRUE);NULL},error=function(e)e)
  stopifnot(inherits(error,"error"))
  stage <- private_build_stage(book)
  file.copy(file.path(book,"exercises"),stage,recursive=TRUE)
  setwd(stage); configure_edition(TRUE)
  instructor <- as.character(render_exercises("basics"))
  stopifnot(grepl("PRIVATE_HINT",instructor),grepl("PRIVATE_ANSWER",instructor),
    grepl("**Solution**",instructor,fixed=TRUE),grepl("Find the mean",instructor))
  configure_edition(FALSE)
  stopifnot(!grepl("PRIVATE_",as.character(render_exercises("basics"))))
  unlink(private,recursive=TRUE)
  setwd(book);configure_edition(FALSE)
  stopifnot(!grepl("PRIVATE_",as.character(render_exercises("basics"))))
  error <- tryCatch({configure_edition(TRUE);NULL},error=function(e)e)
  stopifnot(inherits(error,"error"))
  cat("Student/instructor edition separation checks passed.\n")
},finally={setwd(original);unlink(fixture,recursive=TRUE)})
