<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Central Limit Theorem | Econometrics and Statistics</title>
  <meta name="description" content="This course covers various topics in econometrics. Simulations and real-data-based examples are provided." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Central Limit Theorem | Econometrics and Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This course covers various topics in econometrics. Simulations and real-data-based examples are provided." />
  <meta name="github-repo" content="jrenne/EcoStat" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Central Limit Theorem | Econometrics and Statistics" />
  
  <meta name="twitter:description" content="This course covers various topics in econometrics. Simulations and real-data-based examples are provided." />
  

<meta name="author" content="Jean-Paul Renne" />


<meta name="date" content="2026-09-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="Basics.html"/>
<link rel="next" href="Tests.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/codefolding-lua-1.1/codefolding-lua.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Econometrics and Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="Basics.html"><a href="Basics.html"><i class="fa fa-check"></i><b>1</b> Basic statistical results</a>
<ul>
<li class="chapter" data-level="1.1" data-path="Basics.html"><a href="Basics.html#basics-moments"><i class="fa fa-check"></i><b>1.1</b> Expectations, covariance, and conditional probabilities</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="Basics.html"><a href="Basics.html#basics-bayes"><i class="fa fa-check"></i><b>1.1.1</b> Bayes’ rule</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="Basics.html"><a href="Basics.html#basics-densities"><i class="fa fa-check"></i><b>1.2</b> Cumulative distribution and probability density functions</a></li>
<li class="chapter" data-level="1.3" data-path="Basics.html"><a href="Basics.html#basics-iterated-expectations"><i class="fa fa-check"></i><b>1.3</b> Law of iterated expectations</a></li>
<li class="chapter" data-level="1.4" data-path="Basics.html"><a href="Basics.html#basics-total-variance"><i class="fa fa-check"></i><b>1.4</b> Law of total variance</a></li>
<li class="chapter" data-level="1.5" data-path="Basics.html"><a href="Basics.html#basics-estimators"><i class="fa fa-check"></i><b>1.5</b> Bias, accuracy, and consistency</a></li>
<li class="chapter" data-level="" data-path="Basics.html"><a href="Basics.html#chapter-recap"><i class="fa fa-check"></i>Chapter recap</a></li>
<li class="chapter" data-level="1.6" data-path="Basics.html"><a href="Basics.html#basics-exercises"><i class="fa fa-check"></i><b>1.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="TCL.html"><a href="TCL.html"><i class="fa fa-check"></i><b>2</b> Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="2.1" data-path="TCL.html"><a href="TCL.html#law-of-large-numbers"><i class="fa fa-check"></i><b>2.1</b> Law of large numbers</a></li>
<li class="chapter" data-level="2.2" data-path="TCL.html"><a href="TCL.html#central-limit-theorem-clt"><i class="fa fa-check"></i><b>2.2</b> Central Limit Theorem (CLT)</a></li>
<li class="chapter" data-level="2.3" data-path="TCL.html"><a href="TCL.html#comparison-of-sample-means"><i class="fa fa-check"></i><b>2.3</b> Comparison of sample means</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Tests.html"><a href="Tests.html"><i class="fa fa-check"></i><b>3</b> Statistical tests</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Tests.html"><a href="Tests.html#size-and-power-of-a-test"><i class="fa fa-check"></i><b>3.1</b> Size and power of a test</a></li>
<li class="chapter" data-level="3.2" data-path="Tests.html"><a href="Tests.html#the-different-types-of-statistical-tests"><i class="fa fa-check"></i><b>3.2</b> The different types of statistical tests</a></li>
<li class="chapter" data-level="3.3" data-path="Tests.html"><a href="Tests.html#asymptotic-properties-of-statistical-tests"><i class="fa fa-check"></i><b>3.3</b> Asymptotic properties of statistical tests</a></li>
<li class="chapter" data-level="3.4" data-path="Tests.html"><a href="Tests.html#example-normality-tests"><i class="fa fa-check"></i><b>3.4</b> Example: Normality tests</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ChapterLS.html"><a href="ChapterLS.html"><i class="fa fa-check"></i><b>4</b> Linear Regressions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ChapterLS.html"><a href="ChapterLS.html#linearHyp"><i class="fa fa-check"></i><b>4.1</b> Hypotheses</a></li>
<li class="chapter" data-level="4.2" data-path="ChapterLS.html"><a href="ChapterLS.html#LSquares"><i class="fa fa-check"></i><b>4.2</b> Least square estimation</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="ChapterLS.html"><a href="ChapterLS.html#derivation-of-the-ols-formula"><i class="fa fa-check"></i><b>4.2.1</b> Derivation of the OLS formula</a></li>
<li class="chapter" data-level="4.2.2" data-path="ChapterLS.html"><a href="ChapterLS.html#properties-of-the-ols-estimate-small-sample"><i class="fa fa-check"></i><b>4.2.2</b> Properties of the OLS estimate (small sample)</a></li>
<li class="chapter" data-level="4.2.3" data-path="ChapterLS.html"><a href="ChapterLS.html#goodness-of-fit"><i class="fa fa-check"></i><b>4.2.3</b> Goodness of fit</a></li>
<li class="chapter" data-level="4.2.4" data-path="ChapterLS.html"><a href="ChapterLS.html#inference-and-confidence-intervals-in-small-sample"><i class="fa fa-check"></i><b>4.2.4</b> Inference and confidence intervals (in small sample)</a></li>
<li class="chapter" data-level="4.2.5" data-path="ChapterLS.html"><a href="ChapterLS.html#Ftest"><i class="fa fa-check"></i><b>4.2.5</b> Testing a set of linear restrictions</a></li>
<li class="chapter" data-level="4.2.6" data-path="ChapterLS.html"><a href="ChapterLS.html#largeSample"><i class="fa fa-check"></i><b>4.2.6</b> Large Sample Properties</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ChapterLS.html"><a href="ChapterLS.html#CommonPitfalls"><i class="fa fa-check"></i><b>4.3</b> Common pitfalls in linear regressions</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="ChapterLS.html"><a href="ChapterLS.html#multicollinearity"><i class="fa fa-check"></i><b>4.3.1</b> Multicollinearity</a></li>
<li class="chapter" data-level="4.3.2" data-path="ChapterLS.html"><a href="ChapterLS.html#Omitted"><i class="fa fa-check"></i><b>4.3.2</b> Omitted variables</a></li>
<li class="chapter" data-level="4.3.3" data-path="ChapterLS.html"><a href="ChapterLS.html#irrelevant"><i class="fa fa-check"></i><b>4.3.3</b> Irrelevant variable</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ChapterLS.html"><a href="ChapterLS.html#IV"><i class="fa fa-check"></i><b>4.4</b> Instrumental Variables</a></li>
<li class="chapter" data-level="4.5" data-path="ChapterLS.html"><a href="ChapterLS.html#general-regression-model-grm-and-robust-covariance-matrices"><i class="fa fa-check"></i><b>4.5</b> General Regression Model (GRM) and robust covariance matrices</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="ChapterLS.html"><a href="ChapterLS.html#presentation-of-the-general-regression-model-grm"><i class="fa fa-check"></i><b>4.5.1</b> Presentation of the General Regression Model (GRM)</a></li>
<li class="chapter" data-level="4.5.2" data-path="ChapterLS.html"><a href="ChapterLS.html#GLS"><i class="fa fa-check"></i><b>4.5.2</b> Generalized Least Squares</a></li>
<li class="chapter" data-level="4.5.3" data-path="ChapterLS.html"><a href="ChapterLS.html#asymptotic-properties-of-the-ols-estimator-in-the-grm-framework"><i class="fa fa-check"></i><b>4.5.3</b> Asymptotic properties of the OLS estimator in the GRM framework</a></li>
<li class="chapter" data-level="4.5.4" data-path="ChapterLS.html"><a href="ChapterLS.html#HAC"><i class="fa fa-check"></i><b>4.5.4</b> HAC-robust covariance matrices</a></li>
<li class="chapter" data-level="4.5.5" data-path="ChapterLS.html"><a href="ChapterLS.html#Clusters"><i class="fa fa-check"></i><b>4.5.5</b> Cluster-robust covariance matrices</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ChapterLS.html"><a href="ChapterLS.html#shrinkage-methods"><i class="fa fa-check"></i><b>4.6</b> Shrinkage methods</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="Panel.html"><a href="Panel.html"><i class="fa fa-check"></i><b>5</b> Panel regressions</a>
<ul>
<li class="chapter" data-level="5.1" data-path="Panel.html"><a href="Panel.html#specification-and-notations"><i class="fa fa-check"></i><b>5.1</b> Specification and notations</a></li>
<li class="chapter" data-level="5.2" data-path="Panel.html"><a href="Panel.html#three-standard-cases"><i class="fa fa-check"></i><b>5.2</b> Three standard cases</a></li>
<li class="chapter" data-level="5.3" data-path="Panel.html"><a href="Panel.html#FixedEffect"><i class="fa fa-check"></i><b>5.3</b> Estimation of Fixed-Effects Models</a></li>
<li class="chapter" data-level="5.4" data-path="Panel.html"><a href="Panel.html#RandomEffect"><i class="fa fa-check"></i><b>5.4</b> Estimation of random effects models</a></li>
<li class="chapter" data-level="5.5" data-path="Panel.html"><a href="Panel.html#DynPanel"><i class="fa fa-check"></i><b>5.5</b> Dynamic Panel Regressions</a></li>
<li class="chapter" data-level="5.6" data-path="Panel.html"><a href="Panel.html#introduction-to-program-evaluation"><i class="fa fa-check"></i><b>5.6</b> Introduction to program evaluation</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="Panel.html"><a href="Panel.html#presentation-of-the-problem"><i class="fa fa-check"></i><b>5.6.1</b> Presentation of the problem</a></li>
<li class="chapter" data-level="5.6.2" data-path="Panel.html"><a href="Panel.html#randomized-controlled-trials-rcts"><i class="fa fa-check"></i><b>5.6.2</b> Randomized controlled trials (RCTs)</a></li>
<li class="chapter" data-level="5.6.3" data-path="Panel.html"><a href="Panel.html#difference-in-difference-did-approach"><i class="fa fa-check"></i><b>5.6.3</b> Difference-in-Difference (DiD) approach</a></li>
<li class="chapter" data-level="5.6.4" data-path="Panel.html"><a href="Panel.html#application-of-the-did-approach"><i class="fa fa-check"></i><b>5.6.4</b> Application of the DiD approach</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estimation-methods.html"><a href="estimation-methods.html"><i class="fa fa-check"></i><b>6</b> Estimation Methods</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estimation-methods.html"><a href="estimation-methods.html#secGMM"><i class="fa fa-check"></i><b>6.1</b> Generalized Method of Moments (GMM)</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="estimation-methods.html"><a href="estimation-methods.html#definition-of-the-gmm-estimator"><i class="fa fa-check"></i><b>6.1.1</b> Definition of the GMM estimator</a></li>
<li class="chapter" data-level="6.1.2" data-path="estimation-methods.html"><a href="estimation-methods.html#asymptotic-distribution-of-the-gmm-estimator"><i class="fa fa-check"></i><b>6.1.2</b> Asymptotic distribution of the GMM estimator</a></li>
<li class="chapter" data-level="6.1.3" data-path="estimation-methods.html"><a href="estimation-methods.html#overidentif"><i class="fa fa-check"></i><b>6.1.3</b> Testing hypotheses in the GMM framework</a></li>
<li class="chapter" data-level="6.1.4" data-path="estimation-methods.html"><a href="estimation-methods.html#example-estimation-of-the-stochastic-discount-factor-s.d.f."><i class="fa fa-check"></i><b>6.1.4</b> Example: Estimation of the Stochastic Discount Factor (s.d.f.)</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="estimation-methods.html"><a href="estimation-methods.html#secMLE"><i class="fa fa-check"></i><b>6.2</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="estimation-methods.html"><a href="estimation-methods.html#intuition"><i class="fa fa-check"></i><b>6.2.1</b> Intuition</a></li>
<li class="chapter" data-level="6.2.2" data-path="estimation-methods.html"><a href="estimation-methods.html#definition-and-properties"><i class="fa fa-check"></i><b>6.2.2</b> Definition and properties</a></li>
<li class="chapter" data-level="6.2.3" data-path="estimation-methods.html"><a href="estimation-methods.html#to-sum-up-mle-in-practice"><i class="fa fa-check"></i><b>6.2.3</b> To sum up – MLE in practice</a></li>
<li class="chapter" data-level="6.2.4" data-path="estimation-methods.html"><a href="estimation-methods.html#example-mle-estimation-of-a-mixture-of-gaussian-distribution"><i class="fa fa-check"></i><b>6.2.4</b> Example: MLE estimation of a mixture of Gaussian distribution</a></li>
<li class="chapter" data-level="6.2.5" data-path="estimation-methods.html"><a href="estimation-methods.html#TestMLE"><i class="fa fa-check"></i><b>6.2.5</b> Test procedures</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="estimation-methods.html"><a href="estimation-methods.html#bayesian-approach"><i class="fa fa-check"></i><b>6.3</b> Bayesian approach</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="estimation-methods.html"><a href="estimation-methods.html#introduction"><i class="fa fa-check"></i><b>6.3.1</b> Introduction</a></li>
<li class="chapter" data-level="6.3.2" data-path="estimation-methods.html"><a href="estimation-methods.html#monte-carlo-markov-chains"><i class="fa fa-check"></i><b>6.3.2</b> Monte-Carlo Markov Chains</a></li>
<li class="chapter" data-level="6.3.3" data-path="estimation-methods.html"><a href="estimation-methods.html#example-ar1-specification"><i class="fa fa-check"></i><b>6.3.3</b> Example: AR(1) specification</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="binary-choice-models.html"><a href="binary-choice-models.html"><i class="fa fa-check"></i><b>7</b> Binary-choice models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="binary-choice-models.html"><a href="binary-choice-models.html#latent"><i class="fa fa-check"></i><b>7.1</b> Interpretation in terms of latent variable, and utility-based models</a></li>
<li class="chapter" data-level="7.2" data-path="binary-choice-models.html"><a href="binary-choice-models.html#Avregressors"><i class="fa fa-check"></i><b>7.2</b> Alternative-Varying Regressors</a></li>
<li class="chapter" data-level="7.3" data-path="binary-choice-models.html"><a href="binary-choice-models.html#estimation"><i class="fa fa-check"></i><b>7.3</b> Estimation</a></li>
<li class="chapter" data-level="7.4" data-path="binary-choice-models.html"><a href="binary-choice-models.html#marginalFX"><i class="fa fa-check"></i><b>7.4</b> Marginal effects</a></li>
<li class="chapter" data-level="7.5" data-path="binary-choice-models.html"><a href="binary-choice-models.html#goodness-of-fit-1"><i class="fa fa-check"></i><b>7.5</b> Goodness of fit</a></li>
<li class="chapter" data-level="7.6" data-path="binary-choice-models.html"><a href="binary-choice-models.html#predictions-and-roc-curves"><i class="fa fa-check"></i><b>7.6</b> Predictions and ROC curves</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="TS.html"><a href="TS.html"><i class="fa fa-check"></i><b>8</b> Time Series</a>
<ul>
<li class="chapter" data-level="8.1" data-path="TS.html"><a href="TS.html#introduction-to-time-series"><i class="fa fa-check"></i><b>8.1</b> Introduction to time series</a></li>
<li class="chapter" data-level="8.2" data-path="TS.html"><a href="TS.html#univariate-processes"><i class="fa fa-check"></i><b>8.2</b> Univariate processes</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="TS.html"><a href="TS.html#moving-average-ma-processes"><i class="fa fa-check"></i><b>8.2.1</b> Moving Average (MA) processes</a></li>
<li class="chapter" data-level="8.2.2" data-path="TS.html"><a href="TS.html#ARsection"><i class="fa fa-check"></i><b>8.2.2</b> Auto-Regressive (AR) processes</a></li>
<li class="chapter" data-level="8.2.3" data-path="TS.html"><a href="TS.html#PACFapproach"><i class="fa fa-check"></i><b>8.2.3</b> PACF approach to identify AR/MA processes</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="TS.html"><a href="TS.html#forecasting"><i class="fa fa-check"></i><b>8.3</b> Forecasting</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="append.html"><a href="append.html"><i class="fa fa-check"></i><b>9</b> Appendix</a>
<ul>
<li class="chapter" data-level="9.1" data-path="append.html"><a href="append.html#PCAapp"><i class="fa fa-check"></i><b>9.1</b> Principal component analysis (PCA)</a></li>
<li class="chapter" data-level="9.2" data-path="append.html"><a href="append.html#LinAlgebra"><i class="fa fa-check"></i><b>9.2</b> Linear algebra: definitions and results</a></li>
<li class="chapter" data-level="9.3" data-path="append.html"><a href="append.html#variousResults"><i class="fa fa-check"></i><b>9.3</b> Statistical analysis: definitions and results</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="append.html"><a href="append.html#moments-and-statistics"><i class="fa fa-check"></i><b>9.3.1</b> Moments and statistics</a></li>
<li class="chapter" data-level="9.3.2" data-path="append.html"><a href="append.html#standard-distributions"><i class="fa fa-check"></i><b>9.3.2</b> Standard distributions</a></li>
<li class="chapter" data-level="9.3.3" data-path="append.html"><a href="append.html#StochConvergences"><i class="fa fa-check"></i><b>9.3.3</b> Stochastic convergences</a></li>
<li class="chapter" data-level="9.3.4" data-path="append.html"><a href="append.html#CLTappend"><i class="fa fa-check"></i><b>9.3.4</b> Central limit theorem</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="append.html"><a href="append.html#GaussianVar"><i class="fa fa-check"></i><b>9.4</b> Some properties of Gaussian variables</a></li>
<li class="chapter" data-level="9.5" data-path="append.html"><a href="append.html#AppendixProof"><i class="fa fa-check"></i><b>9.5</b> Proofs</a></li>
<li class="chapter" data-level="9.6" data-path="append.html"><a href="append.html#statistical-tables"><i class="fa fa-check"></i><b>9.6</b> Statistical Tables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Econometrics and Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="TCL" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Central Limit Theorem<a href="TCL.html#TCL" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The law of large numbers (LLN) and the central limit theorem (CLT) are two fundamental theorems of probability. The former states that the sample mean converges in probability to the population mean (when it exists). The latter states that the distribution of the sum (or average) of a large number of independent, identically distributed (i.i.d.) variables with finite variance is approximately normal, regardless of the underlying distribution (as long as it features a finite variance).</p>
<div id="law-of-large-numbers" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Law of large numbers<a href="TCL.html#law-of-large-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="definition">
<p><span id="def:smplpop" class="definition"><strong>Definition 2.1  (Sample and Population) </strong></span>In statistics, a <em>sample</em> refers to a finite set of observations drawn from a <em>population</em>.</p>
</div>
<p>Most of the time, it is necessary to use samples for research, because it is impractical to study the whole population. Typically, it is rare to observe the population mean, and we often use instead sample means (or averages). The sample average of <span class="math inline">\(\{x_1,\dots,x_n\}\)</span> is given by:
<span class="math display">\[
\overline{x}_n = \frac{1}{n}\sum_{i=1}^n x_i.
\]</span>
This sample mean is an estimator of the true (population) mean <span class="math inline">\(\mathbb{E}(x_i)\)</span> (assuming the latter exists). According to the law of large numbers (Theorem <a href="TCL.html#thm:LLN">2.1</a>), this estimator is <em>consistent</em>. (see Def. <a href="append.html#def:convergenceproba">9.16</a> for the definition of convergence in probability.)</p>
<div class="theorem">
<p><span id="thm:LLN" class="theorem"><strong>Theorem 2.1  (Law of large numbers) </strong></span>If the random variables <span class="math inline">\(x_i\)</span> are i.i.d. and if <span class="math inline">\(\mathbb{E}(x_i)=\mu &lt; \infty\)</span>, then the sample mean (<span class="math inline">\(\overline{x}_n\)</span>) is a consistent estimator of the population mean (<span class="math inline">\(\mu\)</span>). In other words, the sample mean converges in probability to the population mean.</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-4" class="proof"><em>Proof</em>. </span>See Appendix <a href="append.html#CLTappend">9.3.4</a>.</p>
</div>
<div class="example">
<p><span id="exm:doctorVisits" class="example"><strong>Example 2.1  </strong></span>Suppose one is interested in the average number of doctor consultations over 12 months, for Swiss people. One can get an estimate by computing the sample average of a large dataset, for instance using the <a href="https://forscenter.ch/projects/swiss-household-panel/">Swiss Household Panel (SHP)</a>:</p>
<p>Figure <a href="TCL.html#fig:incomeDistri">2.1</a> shows the empirical distribution of the number of doctor visits.</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="TCL.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(AEC) <span class="co"># to load the shp data-frame.</span></span>
<span id="cb3-2"><a href="TCL.html#cb3-2" tabindex="-1"></a>shp <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">zap_labels</span>(AEC<span class="sc">::</span>shp) <span class="co"># retain values, remove import-only labels</span></span>
<span id="cb3-3"><a href="TCL.html#cb3-3" tabindex="-1"></a>Nb.doct.visits <span class="ot">&lt;-</span> shp<span class="sc">$</span>p19c15</span>
<span id="cb3-4"><a href="TCL.html#cb3-4" tabindex="-1"></a>Nb.doct.visits <span class="ot">&lt;-</span> Nb.doct.visits[Nb.doct.visits<span class="sc">&gt;=</span><span class="dv">0</span>] <span class="co"># remove irrelevant observations</span></span>
<span id="cb3-5"><a href="TCL.html#cb3-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">plt=</span><span class="fu">c</span>(.<span class="dv">15</span>,.<span class="dv">95</span>,.<span class="dv">2</span>,.<span class="dv">95</span>))</span>
<span id="cb3-6"><a href="TCL.html#cb3-6" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(Nb.doct.visits),<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">25</span>))</span></code></pre></div>
</details>
<div class="figure" style="text-align: left"><span style="display:block;" id="fig:incomeDistri"></span>
<img src="EcoStat_files/figure-html/incomeDistri-1.png" alt="Distribution of the number of doctor visits. Source: Swiss Household Panel." width="672" />
<p class="caption">
Figure 2.1: Distribution of the number of doctor visits. Source: Swiss Household Panel.
</p>
</div>
<p>Let us compute the sample mean, variance, and standard deviation:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="TCL.html#cb4-1" tabindex="-1"></a><span class="fu">data_table</span>(<span class="fu">data.frame</span>(<span class="at">Mean=</span><span class="fu">mean</span>(Nb.doct.visits),</span>
<span id="cb4-2"><a href="TCL.html#cb4-2" tabindex="-1"></a>                      <span class="at">Variance=</span><span class="fu">var</span>(Nb.doct.visits), <span class="at">SD=</span><span class="fu">sd</span>(Nb.doct.visits)), <span class="at">digits=</span><span class="dv">3</span>)</span></code></pre></div>
</details>
<div class="course-table" role="region" aria-label="Data table" tabindex="0">
<table>
<thead>
<tr>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Variance
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5.254
</td>
<td style="text-align:right;">
79.506
</td>
<td style="text-align:right;">
8.917
</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>How to know whether the sample mean is a good estimate of the true (population) average? In other words, how to measure the accuracy of the estimator?</p>
<p>A first answer is provided by the Chebychev inequality. Assume the <span class="math inline">\(x_i\)</span>’s are independently drawn from a distribution of mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. We have:
<span class="math display">\[
\mathbb{E}(\bar{x}_n) = \mu \quad \mbox{ and } \quad \mathbb{V}ar(\mu - \bar{x}_n) = \frac{1}{n}\sigma^2 \underset{n \rightarrow \infty}{\rightarrow} 0.
\]</span>
The Chebychev inequality (Proposition <a href="append.html#prp:chebychev">9.11</a>) states that, for any <span class="math inline">\(\varepsilon &gt; 0\)</span> (even very small), we have:
<span class="math display">\[
\mathbb{P}(|\bar{x}_n-\mu|&gt;\varepsilon) \le \frac{\mathbb{V}ar(\mu - \bar{x}_n)}{\varepsilon^2} = \frac{\sigma^2}{n\varepsilon^2} \underset{n \rightarrow \infty}{\rightarrow} 0.
\]</span>
Consider for instance the estimation of the average number of doctor visits (Example <a href="TCL.html#exm:doctorVisits">2.1</a>). In this example, the sample length is <span class="math inline">\(n=\)</span> 4389, we have <span class="math inline">\(\bar{x}_n=\)</span> 5.25, and the variance <span class="math inline">\(\sigma^2\)</span> was approximately equal to 79.51. Therefore, taking <span class="math inline">\(\varepsilon=0.5\)</span>, we have that <span class="math inline">\(\mathbb{P}(|\bar{x}_n-\mu|&gt;\varepsilon)\)</span> is lower than <span class="math inline">\(\frac{\sigma^2}{n\varepsilon^2} \approx\)</span>
0.072.</p>
<p>However, this only gives bounds for such probabilities. The central limit theorem provides richer information, as it gives the approximate distribution of the estimation error.</p>
</div>
<div id="central-limit-theorem-clt" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Central Limit Theorem (CLT)<a href="TCL.html#central-limit-theorem-clt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="theorem">
<p><span id="thm:LindbergLevyCLT" class="theorem"><strong>Theorem 2.2  (Lindberg-Levy Central limit theorem, CLT) </strong></span>If <span class="math inline">\(x_n\)</span> is an i.i.d. sequence of random variables with mean <span class="math inline">\(\mu\)</span> and (finite) variance <span class="math inline">\(\sigma^2\)</span>, then:
<span class="math display">\[
\boxed{\sqrt{n} (\bar{x}_n - \mu) \overset{d}{\rightarrow} \mathcal{N}(0,\sigma^2), \quad \mbox{where} \quad \bar{x}_n = \frac{1}{n} \sum_{i=1}^{n} x_i.}
\]</span>
[“<span class="math inline">\(\overset{d}{\rightarrow}\)</span>” denotes the convergence in distribution (see Def. <a href="append.html#def:cvgceDistri">9.19</a>)]</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-5" class="proof"><em>Proof</em>. </span>See Appendix <a href="append.html#CLTappend">9.3.4</a>.</p>
</div>
<p>According to the CLT, when <span class="math inline">\(n\)</span> is large and whatever the distribution of the <span class="math inline">\(x_i\)</span>’s (as long as it features an average <span class="math inline">\(\mu\)</span> and a variance <span class="math inline">\(\sigma^2\)</span>), the error between <span class="math inline">\(\bar{x}_n\)</span> and <span class="math inline">\(\mu\)</span> can be seen as a random variable that is normally distributed; it is of mean zero and its standard deviation is <span class="math inline">\(\sigma/\sqrt{n}\)</span>. (We then say that the convergence rate is <em>in <span class="math inline">\(\sqrt{n}\)</span></em>.) The knowledge of the quantiles of the normal distribution can then be used to compute approximate confidence intervals for <span class="math inline">\(\mu\)</span> (based on the sample <span class="math inline">\(\{x_1,\dots,x_n\}\)</span>).</p>
<p>This <a href="https://jrenne.shinyapps.io/StatEcoII/">web interface</a> illustrates the CLT with simulations (select the “CLT” block).</p>
<p>The CL theorem was first postulated by the mathematician Abraham de Moivre. In an article published in 1733, he used the normal distribution to approximate the distribution of the number of heads resulting from many tosses of a fair coin. This finding was nearly forgotten until Pierre-Simon Laplace recalled it in his <a href="https://archive.org/details/thorieanalytiqu01laplgoog">Théorie analytique des probabilités</a>, published in 1812. Laplace expanded De Moivre’s finding by approximating the binomial distribution with the normal distribution.</p>
<div class="exercise">
<p><span id="exr:ExoBuffon" class="exercise"><strong>Exercise 2.1  </strong></span>Consider Buffon’s experiment (Example <a href="Basics.html#exm:Buffon">1.2</a>). We have seen that <span class="math inline">\(\pi\)</span> can be estimated by counting the fraction of times the needles cross the grooves of the floor.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> Using the CLT, determine the (approximate) minimal number <span class="math inline">\(n\)</span> of needles that one has to throw to get an estimate <span class="math inline">\(\hat\pi\)</span> (<span class="math inline">\(= 1/\bar{X}_n\)</span>) of <span class="math inline">\(\pi\)</span> that is such that there is a 95% chance that <span class="math inline">\(\pi \in [\hat\pi-0.01,\hat\pi+0.01]\)</span>?</p>
</div>
<div class="exercise">
<p><span id="exr:ExoPileFace" class="exercise"><strong>Exercise 2.2  </strong></span>Assume you have a lot of time and a coin. How would you approximate the 100 percentiles of the <span class="math inline">\(\mathcal{N}(0,1)\)</span> distribution?</p>
</div>
<p>The CLT can be extended to the case where each <span class="math inline">\(x_i\)</span> is a vector. (In that case, and if the dimension of <span class="math inline">\(x_i\)</span> is <span class="math inline">\(m\)</span>, then <span class="math inline">\(\mathbb{V}ar(x_i)\)</span> is a <span class="math inline">\(m\times m\)</span> matrix.) Here is the multivariate CLT:</p>
<div class="theorem">
<p><span id="thm:MCLT" class="theorem"><strong>Theorem 2.3  (Multivariate Central limit theorem, CLT) </strong></span>If <span class="math inline">\(\mathbf{x}_n\)</span> is an i.i.d. sequence of <span class="math inline">\(m\)</span>-dimensional random variables with mean <span class="math inline">\(\boldsymbol\mu\)</span> and variance <span class="math inline">\(\Sigma\)</span>, where <span class="math inline">\(\Sigma\)</span> is a positive definite matrix, then:
<span class="math display">\[
\boxed{\sqrt{n} (\bar{\mathbf{x}}_n - \boldsymbol\mu) \overset{d}{\rightarrow} \mathcal{N}(\mathbf{0},\Sigma), \quad \mbox{where} \quad \bar{\mathbf{x}}_n = \frac{1}{n} \sum_{i=1}^{n} \mathbf{x}_i.}
\]</span></p>
</div>
</div>
<div id="comparison-of-sample-means" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Comparison of sample means<a href="TCL.html#comparison-of-sample-means" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As said at the beginning of this chapter, the CLT is a key statistical result that has numerous applications. An important one is the statistical comparision of sample means:</p>
<p>Consider two samples <span class="math inline">\(\{m_1,\dots,m_{n_m}\}\)</span> and <span class="math inline">\(\{w_1,\dots,w_{n_w}\}\)</span>. Assume that the <span class="math inline">\(m_i\)</span>’s (respectively the <span class="math inline">\(w_i\)</span>’s) are i.i.d., with mean <span class="math inline">\(\mu_m\)</span> and variance <span class="math inline">\(\sigma^2_m\)</span> and of <span class="math inline">\(w_i\)</span>’s (resp. with mean <span class="math inline">\(\mu_w\)</span> and variance <span class="math inline">\(\sigma^2_w\)</span>).</p>
<p>If <span class="math inline">\(n\)</span> is large, according to the CLT, we approximately have:
<span class="math display">\[
\sqrt{n_m}(\bar{m} - \mu_m) \sim \mathcal{N}(0,\sigma^2_m) \quad and \quad \sqrt{n_w}(\bar{w} - \mu_w) \sim \mathcal{N}(0,\sigma^2_w),
\]</span>
or
<span class="math display">\[
\bar{m} \sim \mathcal{N}\left(\mu_m,\frac{\sigma^2_m}{n_m}\right) \quad and \quad \bar{w} \sim \mathcal{N}\left(\mu_w,\frac{\sigma^2_w}{n_w}\right).
\]</span></p>
<p>if the <span class="math inline">\(m_i\)</span>’s and the <span class="math inline">\(w_i\)</span>’s are independent, then <span class="math inline">\(\bar{m}\)</span> and <span class="math inline">\(\bar{w}\)</span> also are, and we get:
<span class="math display">\[
\bar{m} - \bar{w} \sim \mathcal{N}\left(\mu_m-\mu_w,\sigma^2\right) \quad with \quad \sigma^2 = \frac{\sigma^2_m}{n_m}+\frac{\sigma^2_w}{n_w}.
\]</span>
This can be used to test the null hypothesis <span class="math inline">\(H_0: \; \mu_m-\mu_w = 0\)</span> (see Section <a href="Tests.html#Tests">3</a>). Indeed under this assumption, the probability that <span class="math inline">\(\bar{m} - \bar{w}\)</span> is in <span class="math inline">\([-1.96\sigma,1.96\sigma]\)</span> (respectively in <span class="math inline">\([-2.58\sigma,2.58\sigma]\)</span>) is approximately 0.95 (respectively 0.99) [see Table <a href="append.html#tab:Normal">9.1</a>].</p>
<p>For instance, if we find, using our sample, that <span class="math inline">\(\bar{m} - \bar{w}\)</span> is not in <span class="math inline">\([-2.58\sigma,2.58\sigma]\)</span>, then we reject the null hypothesis at the 1% significance level.</p>
<div class="example">
<p><span id="exm:comparSmplMeans" class="example"><strong>Example 2.2  (Comparison of sample means) </strong></span>Let us use the <a href="https://forscenter.ch/projects/swiss-household-panel/">Swiss Household Panel (SHP)</a> dataset to test the equality between men and women incomes, for Swiss people under the age of 35.</p>
<p>The next lines of codes construct two samples of incomes; one for men (<code>income.m</code>), and one for women (<code>income.w</code>).</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="TCL.html#cb5-1" tabindex="-1"></a><span class="fu">library</span>(AEC);<span class="fu">library</span>(logKDE)</span></code></pre></div>
</details>
<pre><code>## Warning: package &#39;logKDE&#39; was built under R version 4.5.2</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="TCL.html#cb7-1" tabindex="-1"></a>dataset.m <span class="ot">&lt;-</span> <span class="fu">subset</span>(shp,(sex19<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(age19<span class="sc">&lt;=</span><span class="dv">35</span>))</span>
<span id="cb7-2"><a href="TCL.html#cb7-2" tabindex="-1"></a>dataset.w <span class="ot">&lt;-</span> <span class="fu">subset</span>(shp,(sex19<span class="sc">==</span><span class="dv">2</span>)<span class="sc">&amp;</span>(age19<span class="sc">&lt;=</span><span class="dv">35</span>))</span>
<span id="cb7-3"><a href="TCL.html#cb7-3" tabindex="-1"></a>income.m <span class="ot">&lt;-</span> dataset.m<span class="sc">$</span>i19ptotg</span>
<span id="cb7-4"><a href="TCL.html#cb7-4" tabindex="-1"></a>income.w <span class="ot">&lt;-</span> dataset.w<span class="sc">$</span>i19ptotg</span>
<span id="cb7-5"><a href="TCL.html#cb7-5" tabindex="-1"></a>income.m <span class="ot">&lt;-</span> income.m[income.m<span class="sc">&gt;=</span><span class="dv">0</span>] <span class="co"># remove irrelevant data</span></span>
<span id="cb7-6"><a href="TCL.html#cb7-6" tabindex="-1"></a>income.w <span class="ot">&lt;-</span> income.w[income.w<span class="sc">&gt;=</span><span class="dv">0</span>] <span class="co"># remove irrelevant data</span></span></code></pre></div>
</details>
<p>Figure <a href="TCL.html#fig:RcompMeans">2.2</a> displays the empirical densities of incomes for men and women. Vertical dashed lines indicate sample means:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="TCL.html#cb8-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">plt=</span><span class="fu">c</span>(.<span class="dv">1</span>,.<span class="dv">95</span>,.<span class="dv">2</span>,.<span class="dv">95</span>)) <span class="co"># adjust margins</span></span>
<span id="cb8-2"><a href="TCL.html#cb8-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">logdensity</span>(income.w),<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">200000</span>),<span class="at">main=</span><span class="st">&quot;&quot;</span>,</span>
<span id="cb8-3"><a href="TCL.html#cb8-3" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Yearly gross income (in CHF)&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;&quot;</span>) <span class="co"># x and y labels</span></span>
<span id="cb8-4"><a href="TCL.html#cb8-4" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">logdensity</span>(income.m),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb8-5"><a href="TCL.html#cb8-5" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(income.m),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lty=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb8-6"><a href="TCL.html#cb8-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(income.w),<span class="at">col=</span><span class="st">&quot;black&quot;</span>,<span class="at">lty=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb8-7"><a href="TCL.html#cb8-7" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="fu">c</span>(<span class="st">&quot;men yearly income&quot;</span>,<span class="st">&quot;women&quot;</span>),<span class="at">lty=</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;black&quot;</span>))</span></code></pre></div>
</details>
<div class="figure" style="text-align: left"><span style="display:block;" id="fig:RcompMeans"></span>
<img src="EcoStat_files/figure-html/RcompMeans-1.png" alt="Distribution of yearly gross incomes for Swiss residents under the age of 35. Source: SHP. Vertical dashed lines indicates the sample mean." width="672" />
<p class="caption">
Figure 2.2: Distribution of yearly gross incomes for Swiss residents under the age of 35. Source: SHP. Vertical dashed lines indicates the sample mean.
</p>
</div>
<p>Let us compute <span class="math inline">\(\bar{m}\)</span>, <span class="math inline">\(\bar{w}\)</span>, and <span class="math inline">\(\sigma\)</span>:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="TCL.html#cb9-1" tabindex="-1"></a>m.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(income.m)</span>
<span id="cb9-2"><a href="TCL.html#cb9-2" tabindex="-1"></a>w.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(income.w)</span>
<span id="cb9-3"><a href="TCL.html#cb9-3" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(income.m)<span class="sc">/</span><span class="fu">length</span>(income.m) <span class="sc">+</span> <span class="fu">var</span>(income.w)<span class="sc">/</span><span class="fu">length</span>(income.w))</span>
<span id="cb9-4"><a href="TCL.html#cb9-4" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(m.bar,w.bar,sigma))</span></code></pre></div>
</details>
<pre><code>## [1] 53035.023 42708.227  2427.425</code></pre>
<p>Under the “equality assumption”, their would a probability of only 5% (respectively 1%) for <span class="math inline">\(\bar{m} - \bar{w}\)</span> not to be in <span class="math inline">\([\)</span>-4758,4758<span class="math inline">\(]\)</span> (respectively in <span class="math inline">\([\)</span>-6263,6263<span class="math inline">\(]\)</span>). Since <span class="math inline">\(\bar{m} - \bar{w}\)</span> is equal to 10327, we reject the null hypothesis at the 5%, and even 1%, significance levels.</p>
</div>
<!-- %\begin{frame} -->
<!-- %\begin{footnotesize} -->
<!-- %      \begin{figure} -->
<!-- %      \caption{The importance of the independence assumption} -->
<!-- %          \includegraphics[width=1\linewidth]{../../figures/Figure_CLT_indpdce.pdf} -->
<!-- % -->
<!-- %      \begin{tiny} -->
<!-- %      \flushleft{Note: The three samples have been simulated using the following data generating process: $x_i = \mu + \rho (x_{i-1}-\mu) + \sqrt{1-\rho^2}\varepsilon_i$, where $\varepsilon_i \sim \mathcal{N}(0,1)$. Case A: $\rho = 0$;  Case B: $\rho = 0.9$;  Case C: $\rho = 0.99$. In the three cases, $\mathbb{E}(X_i)=\mu=2$ and $\mathbb{V}ar(X_i)=1$.} -->
<!-- %      \end{tiny} -->
<!-- %      \end{figure} -->
<!-- % -->
<!-- %\end{footnotesize} -->
<!-- %\end{frame} -->
<!-- %\begin{frame} -->
<!-- %\begin{footnotesize} -->
<!-- %\begin{exercise}[Polls and confidence intervals] -->
<!-- %\begin{itemize} -->
<!-- %  \item The day before an election with two candidates (A and B), 100 persons are surveyed (randomly chosen). 51\% of them say they will vote for Candidate A. -->
<!-- %  \item[(a)] Assuming people do not change their mind before the vote, compute an approximation of the probability that A will win. -->
<!-- %   -->
<!-- %  (Hints: introduce $\theta$, the score that will be obtained by A; compute $\mathbb{P}(\theta > \mu + \bar{x}_n)$, where $x_i$ is equal to 1 if the $i^{th}$ respondent will votes for A and 0 otherwise). -->
<!-- %  \item[(b)] What is the probability if 55\% of them say they will vote for Candidate A. -->
<!-- %  \item[(c)] What would be that probability if 4000 people had been surveyed? (with 51\%) -->
<!-- %\end{itemize} -->
<!-- %\end{exercise} -->
<!-- %\begin{exercise}[Computer-free simulation of $\mathcal{N}$] -->
<!-- %\begin{itemize} -->
<!-- %  \item Assume you have a lot of time and a coin. How would you approximate the 100 percentiles of the Normal distribution? -->
<!-- %\end{itemize} -->
<!-- %\end{exercise} -->
<!-- %% Research on TCL and Casino: \url{http://digitalscholarship.unlv.edu/cgi/viewcontent.cgi?article=1293&context=grrj} -->
<!-- %\end{footnotesize} -->
<!-- %\end{frame} -->

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>More precisely, the expectation of this fraction is equal to <span class="math inline">\(1/\pi\)</span>.<a href="TCL.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Basics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/jrenne/EcoStat/edit/main/02-CLT.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["EcoStat.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
